### ISSUE TITLE
Uber jar is not deployed to any repository

### ISSUE THREAD

**Issue by Andy-JB** [camunda-community-hub/kafka-connect-zeebe#146] opened 2023-04-19 10:10 UTC
The uber jar does not seem to be deployed to any repository. This does not seems like expected behaviour since the uber jar is required to use the connector with Kafka Connect

**Comment by berndruecker** [comment] 2023-04-19 14:49
Duplicate of https://github.com/camunda-community-hub/kafka-connect-zeebe/issues/147 - let's discuss things there

**Closed by berndruecker** 2023-04-19 14:49 UTC
