### ISSUE TITLE
SMT vs JSONPath

### ISSUE THREAD

**Issue by npepinpe** [camunda-community-hub/kafka-connect-zeebe#11] opened 2019-08-06 08:16 UTC
At the moment we use JSONPath to extract properties from a sink record when transforming it into a Zeebe message.

From what I understand, for our sink connector, we should instead specify the format we want, and users should use [Single Message Transformations](https://docs.confluent.io/current/connect/transforms/index.html) to map their records to our expected format. That's in theory, no idea in practice if users actually make use of this.

**Comment by berndruecker** [comment] 2021-07-13 07:29
Duplicate of  https://github.com/camunda-community-hub/kafka-connect-zeebe/issues/18

**Closed by berndruecker** 2021-07-13 07:29 UTC
Labels: question
